server {
    listen 80;
    listen [::]:80;
    server_name cryptosignals.btkdeals.com;

    root /var/www/cryptosignals;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\.(env|git|ht) {
        deny all;
    }
}
